language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버 Home
# When dependencies are injected by gradle, it cache in a directory and same dependencies don't injected again.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# command after pushing at master branch
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/hello-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # setting value at Travis repo settings
    secret_access_key: $AWS_SECRET_KEY # setting value at Travis repo settings
    bucket: study-hello-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # private access to zip
    local_dir: deploy # the directory which before_deploy makes
    wait-until-deployed: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # setting value at Travis repo settings
      secret_access_key: $AWS_SECRET_KEY # setting value at Travis repo settings
      bucket: study-hello-springboot-build
      key: hello-springboot.zip
      bundle_type: zip
      application: hello-springboot
      deployment_group: hello-springboot-group
      region: ap-northeast-2
      wait-until-deployed: true

# When CI complete, notify by email
notifications:
  email:
    recipients:
      - kha2464@naver.com